# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29da1b696c0ac76da32995f375349fc24efdd79dbd7091b90109e574d2d483fe1c79588caf19868c32ebf2b7b8eea67b95afbe02057fb402101e95c6cbe2bf64

test:
  secret_key_base: 115dba1588a90729fb1bb2e37c7503ac6fd5d722c4c428c8d2a86a8de558f0ab1ec8f11d9cb7043f481e1253dd514e53d192d129d525080495cdd7e7e6629351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
